// tag::excerpt[]
= Qanary Component Fuzzy
:toc:

This is a Qanary component for checking if given NER annotations in a question match specific lubw domain instances via a fuzzy compare.
The component receives prior AnnotationsOfInstance from a NER qanary component via the knowledge graph.
It also receives the domain knowledge via the knowledge graph, which get seeded when asking the question.

.Example Prior NER Annotations in Question:
[source,text]
----
Was war gestern der Luftqaulitätsinndex in Ullm im Durchschnitt repräsentiert als Txt?
                    └┬────────────────┘    └┬─┘    └─────────┬┘                   └┬┘
           AnnotationOfInstance   AnnotationOfInstance   AnnotationOfInstance   AnnotationOfInstance
                 MEASURAND               STATION              CALCULATION          REPRESENTATION
----

.Example Result Fuzzy Match Annotations in Question:
[source,text]
----
Was war gestern der Luftqaulitätsinndex in Ullm im Durchschnitt repräsentiert als Txt?
                    └┬────────────────┘    └┬─┘    └─────────┬┘                   └┬┘
           AnnotationOfMeasurand   AnnotationOfStation   AnnotationOfCalculation   AnnotationOfRepresentation
            Luftqualitätsindex             Ulm                 Durchschnitt                   Text
----

This component uses https://fusejs.io for the fuzzy compare logic and is limited by the possibilities offered by this library.
// end::excerpt[]

include::../../docs/Component Install.adoc[leveloffset=+1]
include::../../docs/Component Environment Variables.adoc[leveloffset=+2]
include::../../docs/Component Integration.adoc[leveloffset=+2]

[source,yaml]
----
include::../../docker-compose.yml[tags=preamble;qanary-pipeline;qanary-component-fuzzy;networks]
----

Keywords prefixed with `$` represent variables and can either be preserved in a `.env` file or must be replaced by plain text.

[source,dotenv]
----
include::../../example.env[tags=qanary-pipeline;qanary-component-core;qanary-component-fuzzy]
----

== Functionality

The component fetches every rdf triple of a `<urn:domain>` class, maps it to an internal representation and checks if previous NER annotations in the question fuzzy match a domain instance.
If so, it adds the domain instance as an annotation to the knowledge graph.

Note that all matches are added to the knowledge graph.
This means that if the question contains multiple domain instances, all of them will be added to the knowledge graph.

Additionally the component logs found domain instances to the console.

No error handling is implemented as this component simply does not add annotations to the knowledge graph if errors occur.

== Usage

Usage, as with all Qanary components, is divided into two phases.
In the first phase, an annotation is requested from the pipeline via the REST interface.
In the second phase, we can get the annotation data via a SPARQL query.

=== Request an annotation

To use the component, you can make a request to the Qanary pipeline.
In the following example, a question is asked to the pipeline in german and domain instances are matched and annotated.

[source,httprequest]
----
include::docs/Usage.http[]
----

=== Receive annotation data

This is a simple SPARQL query to view the annotations of the component.
To execute it, the `endpoint` from the query must be used for annotation.
Additionally, `YOUR_CURRENT_GRAPH_ID` must be replaced by the `inGraph` or `outGraph` of the response.

[source,httprequest]
----
include::docs/Usage.rq[]
----

A client is required to execute this SPARQL query.

=== Example Output

A possible SPARQL client is https://jena.apache.org/documentation/tools/[Apache Jena].
This allows to query the data with the following command line interface:

[source,bash]
----
rsparql --file docs/Usage.rq --service http://qanary-pipeline:40111/sparql --results=CSV
----

For the HTTP query `Was war gestern der Luftqaulitätsinndex in Ullm im Durchschnitt repräsentiert als Txt?` there are the following found annotations in the SPARQL query

[%header,format=csv]
|===
include::docs/Output.csv[]
|===

include::../../docs/Component Annotation.adoc[leveloffset=+1]