image: node:18-alpine

stages:
  - build
  - lint
  - test

build_rasa:
  stage: build
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa train
  artifacts:
    paths:
      - apps/rasa/models
    expire_in: 5 day

build_everything_else:
  stage: build
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run init
    - npm run build
  artifacts:
    paths:
      - "**/dist"
      - "**/.next"
    expire_in: 5 day

lint_rasa:
  stage: lint
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa data validate

lint_everything_else:
  stage: lint
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run init
    - npm run lint

test_rasa:
  stage: test
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa test
  artifacts:
    paths:
      - apps/rasa/results
    expire_in: 5 day


test_everything_else:
  stage: test
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run init
    - npm run test
  artifacts:
    paths:
      - "**/coverage"
    expire_in: 5 day
