image: node:18-alpine

stages:
  - build
  - lint
  - test

build:
  stage: build
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run reinit
  artifacts:
    paths:
      - "node_modules"
      - "**/node_modules"
      - "**/dist"
    expire_in: 5 day

rasa_train:
  stage: build
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa train --domain domain.yml --data data --out models
  artifacts:
    paths:
      - apps/rasa/models
    expire_in: 5 day

lint:
  stage: lint
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run lint
    - npm run format

lint_rasa:
  stage: lint
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa data validate

test:
  stage: test
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run test
  artifacts:
    paths:
      - "**/coverage"
    expire_in: 5 day

test_rasa:
  stage: test
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa test --fail-on-prediction-errors
  artifacts:
    paths:
      - apps/rasa/results
    expire_in: 5 day
