image: node:alpine

stages:
  - docs
  - build
  - lint
  - test
  - rasa
  - rasa_test

build:
  stage: build
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run reinit
  artifacts:
    paths:
      - "**/dist"
    expire_in: 5 day

lint:
  stage: lint
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run init
    - npm run lint
    - npm run format

test:
  stage: test
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run init
    - npm run test:ci
    - /bin/sh .bin/merge-coverage-reports.sh
  artifacts:
    paths:
      - "**/coverage"
    expire_in: 5 day
  coverage: /Statements\s+:\s*([\d\.]+)/

# does not work as qanary-pipeline is not starting correctly
# qanary-tests:
#   stage: test
#   image:
#       name: docker:23.0.1-cli
#       entrypoint: ["/bin/sh", "-c"]
#   before_script:
#     - apk update
#     - apk add bash curl nodejs npm
#     - apk add --no-cache libc6-compat
#   script:
#     - cp example.env .env
#     - echo "127.0.0.1 qanary-pipeline" >> /etc/hosts
#     - echo "0.0.0.0 qanary-pipeline" >> /etc/hosts
#     - npm run init
#     - docker compose down
#     - npm run docker:build
#     - npm run docker:qanary-slim -- --build
#     - cd packages/qanary-quality-assurance
#     - docker build -t qanary_quality_assurance .
#     - docker ps -a
#     # - bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' qanary-pipeline:40111)" != "200" ]]; do sleep 5; done'
#     - npm run qa:ci
#   artifacts:
#     paths:
#       - "**/output"
#     expire_in: 5 day


rasa_train:
  stage: rasa
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa train --domain domain.yml --data data --out models
  artifacts:
    paths:
      - apps/rasa/models
    expire_in: 5 day

lint_rasa:
  stage: rasa
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa data validate

test_rasa:
  stage: rasa_test
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa test
  artifacts:
    paths:
      - apps/rasa/results
    expire_in: 5 day

docs_summary:
  stage: docs
  image:
    name: pandoc/latex
    entrypoint: ["/bin/sh", "-c"]
  script:
    - mkdir output
    - pandoc --standalone --output ./output/Summary.de.pdf ./docs/summary/*.de.md
    - pandoc --standalone --output ./output/Summary.en.pdf ./docs/summary/*.en.md
  artifacts:
    paths:
      - output
