image: node:alpine

stages:
  - docs
  - build
  - lint
  - test
  - rasa
  - rasa_test

build:
  stage: build
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run reinit
  artifacts:
    paths:
      - "**/dist"
    expire_in: 5 day

lint:
  stage: lint
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run init
    - npm run lint
    - npm run format

test:
  stage: test
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run init
    - npm run test:ci
    - /bin/sh .bin/merge-coverage-reports.sh
  artifacts:
    paths:
      - "**/coverage"
    expire_in: 5 day
  coverage: /Statements\s+:\s*([\d\.]+)/

rasa_train:
  stage: rasa
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa train --domain domain.yml --data data --out models
  artifacts:
    paths:
      - apps/rasa/models
    expire_in: 5 day

lint_rasa:
  stage: rasa
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa data validate

test_rasa:
  stage: rasa_test
  image:
    name: rasa/rasa:3.4.0
    entrypoint: [""]
  script:
    - cd apps/rasa
    - rasa test
  artifacts:
    paths:
      - apps/rasa/results
    expire_in: 5 day

docs_summary:
  stage: docs
  image:
    name: pandoc/latex
    entrypoint: ["/bin/sh", "-c"]
  script:
    - mkdir output
    - pandoc --standalone --output ./output/Summary.de.pdf ./docs/summary/*.de.md
    - pandoc --standalone --output ./output/Summary.en.pdf ./docs/summary/*.en.md
  artifacts:
    paths:
      - output
