image: node:18-alpine

stages:
  - build
  - lint
  - test

build:
  stage: build
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run init
  artifacts:
    paths:
      - "**/dist"
      - "**/.next"
    expire_in: 5 day

lint:
  stage: lint
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run init
    - npm run lint -- --filter=!rasa
    - npm run format

test:
  stage: test
  script:
    - apk add --no-cache libc6-compat
    - apk update
    - npm run init
    - npm run test -- --filter=!rasa
  artifacts:
    paths:
      - "**/coverage"
    expire_in: 5 day
