= Abgabedokument

- **Projektname:** Projektgruppe 6 - Umweltinformationen abfragen
- **Tag:** https://gitlab.imn.htwk-leipzig.de/fbahr/quatsch-project-22/-/tree/abgabe
- **Repository:** https://gitlab.imn.htwk-leipzig.de/fbahr/quatsch-project-22

== Dialoge/Fragen-Muster

Die Abfrage der Umweltdaten ist so konzipiert, dass jegliche Anfragen, unabhängig vom aktuellen Stand der Unterhaltung, beantwortet werden können.
Eine Frage, die den vollständigen Informationskontext beinhaltet, kann in folgender Form gestellt werden:

[source]
----
Was ist das <Berechungsverfahren> des <Messgröße> in <Messstation> zwischen <Startzeit> und <Endzeit> repräsentiert als <Representation>?
----

Die Werte der Platzhalter können unter folgendem Link gefunden werden: https://gitlab.imn.htwk-leipzig.de/fbahr/quatsch-project-22/-/tree/main/packages/qanary-lubw-data/src/data

Eine beispielhafte Füllung des obigen Schemas könnte wie folgt aussehen:

[source]
----
Was ist das Maximum des Ozonwerts in Ulm zwischen 01.02.2023 und 15.02.2023 repräsentiert als Text?
----

Umstellungen der Satzstruktur sind natürlich zulässig.

Für eine fortlaufende Unterhaltung wird der Zustand der aktuellen Unterhaltung zwischengespeichert und ergänzt, die darauffolgenden Fragen.
So können in der Unterhaltung unter anderem Frage in folgendem Schema gestellt werden:

[source]
----
Was ist das <Berechungsverfahren>?
----

Eine beispielhafte Füllung des obigen Schemas könnte wie folgt aussehen:

[source]
----
Was ist das Minimum?
----

oder

[source]
----
Was ist der niedrigste Wert?
----

Sofern der notwendige Kontext der Unterhaltung nicht zur Verfügung steht, wird er durch das System aufgebaut.
Das letzte Beispiel kann hierfür in einer neuen Session genutzt werden:

[source]
----
(Neue Session)
Was ist der niedrigste Wert?
----

Eine Auswahl an möglichen Fragen kann den Testfällen der genutzten Technologien entnommen werden.

- Rasa Tests: https://gitlab.imn.htwk-leipzig.de/fbahr/quatsch-project-22/-/tree/main/apps/rasa/tests
- Qanary Tests: https://gitlab.imn.htwk-leipzig.de/fbahr/quatsch-project-22/-/tree/main/packages/qanary-quality-assurance

== Kurzbeschreibung

Die Landesanstalt für Umwelt Baden-Württemberg erfasst in einem Netz aus Messstationen Umweltdaten.
Aus diesen Daten können Beobachtungen abgeleitet werden, um Aussagen über den Zustand der Ökosysteme zu treffen.
Der öffentliche Zugang ermöglicht sowohl Forscher:innen als auch Privatpersonen eine Exploration der beobachteten Biotope.
Die Menge und Komplexität der erfassten Daten erfordert neben einem vereinfachten Zugang für die diversen Benutzergruppen auch eine nachvollziehbare Aufbereitung der Informationen.

Das Ziel dieses Projekts war es, die Umweltdaten über ein Frage-Antwort-System zugänglich zu machen und die korrekte Eingabe mithilfe von Chatbot-Funktionen zu stützen.
Wesentlich hierbei war die Erzeugung eines Kontexts, in welchem eine Frage gestellt werden kann, sodass sie den Anforderungen der Datenquellen entspricht.
Des Weiteren war eine Präzisierung der Frage, die Verarbeitung der Datensätze und dessen Darstellung relevant, um die Zugänglichkeit für den jeweiligen Benutzer zu gewährleisten.

Um die Projektziele zu erfüllen, wurde eine webbasierte Anwendung entwickelt, welche die jeweiligen Anforderungen bedienen kann.
Zur Bearbeitung der Chatbot-Funktionalität wurde der Rasa-Technologie-Stack[^rasa] benutzt, welcher sowohl die Eingabe in einer webbasierten Oberflächen, die Zuweisung von natürlichsprachigen Anfragen zu Computer-Befehlen als auch die Ausführung der Befehle möglich macht.
Das Frage-Antwort-System wurde mithilfe des Qanary-Technologie-Stack[^qanary] umgesetzt.
Diese Technologie ermöglicht es, einzelne Wissensfragmente aus der an das System gestellten Frage zu extrahieren und den Kontext der Frage herzustellen, sodass die Datenquellen abgefragt werden können.
Die Präzisierung der Frage, die Verarbeitung und Darstellung der Datensätze konnte ebenfalls über diesen Mechanismus integriert werden.

Weiterführende Ausführungen zu diesem Projekt können unter https://gitlab.imn.htwk-leipzig.de/fbahr/quatsch-project-22
gefunden werden.

[^rasa]: Der Rasa-Technologiestapel, bestehend aus Rasa-Chat, Rasa Open Source und Rasa Action Server: https://rasa.com/
[^qanary]:
Eine Referenzimplementierung zur Erstellung von Fragebeantwortungssystemen nach der Qanary-Methodik: https://github.com/WDAqua/Qanary

== Teammitglieder

- Florian Gudat
- Frederic Thilo Bahr
- Maximilian Fornaçon
- Sergi Doménech Guzy
