version: "3.0"

services:
  rasa:
    container_name: rasa-bot
    networks: ["rasa-network"]
    ports:
      - "5005:5005"
    build:
      context: ./apps/rasa
    command: >
      run --enable-api --cors "*"

  action-server:
    container_name: action-server
    networks: ["rasa-network"]
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./apps/action-server/Dockerfile
    volumes:
      - ./apps/action-server:/app/apps/action-server
      - /app/apps/action-server/node_modules

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    volumes:
      - ./apps/frontend/src:/app/apps/frontend/src
      - ./apps/frontend/public:/app/apps/frontend/public
    restart: always
    ports:
      - "3000:3000"
    networks:
      - rasa-network

networks: { rasa-network: {} }