version: "3.5"

services:
  qanary-pipeline:
    container_name: qanary-pipeline
    image: qanary/qanary-pipeline:3.7.0
    restart: always
    networks:
      - rasa-network
    ports:
      - "$QANARY_PORT:$QANARY_PORT"
    environment:
      - STARDOG_DATABASE=$STARDOG_DATABASE
      - STARDOG_URL=$STARDOG_URL
      - STARDOG_USERNAME=$STARDOG_USERNAME
      - STARDOG_PASSWORD=$STARDOG_PASSWORD
      - SERVER_HOST=$QANARY_HOST
      - SERVER_PORT=$QANARY_PORT
      - QANARY_PROCESS_ALLOW-ADDITIONAL-TRIPLES=true

  # qanary-component-example1:
  #   container_name: $SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_A_NAME
  #   networks:
  #     - rasa-network
  #   ports:
  #     - "$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_A_PORT:40500"
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: ./apps/qanary-component-example/Dockerfile
  #   environment:
  #     - SPRING_BOOT_ADMIN_URL=$SPRING_BOOT_ADMIN_URL
  #     - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL=http://$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_A_NAME:$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_A_PORT
  #   volumes:
  #     - ./apps/qanary-component-example:/app/apps/qanary-component-example
  #     - /app/apps/qanary-component-example/node_modules
  #     - /app/node_modules

  qanary-component-pm-measurand:
    container_name: $SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_MEASURAND_NAME
    networks:
      - rasa-network
    ports:
      - "$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_MEASURAND_PORT:40500"
    restart: always
    build:
      context: .
      dockerfile: ./apps/qanary-component-pm/Dockerfile
    environment:
      - SPRING_BOOT_ADMIN_URL=$SPRING_BOOT_ADMIN_URL
      - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL=http://$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_MEASURAND_NAME:$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_MEASURAND_PORT
      - QANARY_ORIGIN=$QANARY_HOST:$QANARY_PORT
      - LUBW_DOMAIN=$PM_MEASURAND_DOMAIN
    volumes:
      - ./apps/qanary-component-pm:/app/apps/qanary-component-pm
      - /app/apps/qanary-component-pm/node_modules
      - /app/node_modules
  
  qanary-component-pm-station:
    container_name: $SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_STATION_NAME
    networks:
      - rasa-network
    ports:
      - "$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_STATION_PORT:40500"
    restart: always
    build:
      context: .
      dockerfile: ./apps/qanary-component-pm/Dockerfile
    environment:
      - SPRING_BOOT_ADMIN_URL=$SPRING_BOOT_ADMIN_URL
      - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL=http://$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_STATION_NAME:$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_STATION_PORT
      - QANARY_ORIGIN=$QANARY_HOST:$QANARY_PORT
      - LUBW_DOMAIN=$PM_STATION_DOMAIN
    volumes:
      - ./apps/qanary-component-pm:/app/apps/qanary-component-pm
      - /app/apps/qanary-component-pm/node_modules
      - /app/node_modules

  qanary-component-pm-calculation:
    container_name: $SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_CALCULATION_NAME
    networks:
      - rasa-network
    ports:
      - "$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_CALCULATION_PORT:40500"
    restart: always
    build:
      context: .
      dockerfile: ./apps/qanary-component-pm/Dockerfile
    environment:
      - SPRING_BOOT_ADMIN_URL=$SPRING_BOOT_ADMIN_URL
      - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL=http://$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_CALCULATION_NAME:$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_CALCULATION_PORT
      - QANARY_ORIGIN=$QANARY_HOST:$QANARY_PORT
      - LUBW_DOMAIN=$PM_CALCULATION_DOMAIN
    volumes:
      - ./apps/qanary-component-pm:/app/apps/qanary-component-pm
      - /app/apps/qanary-component-pm/node_modules
      - /app/node_modules

  qanary-component-pm-representation:
    container_name: $SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_REPRESENTATION_NAME
    networks:
      - rasa-network
    ports:
      - "$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_REPRESENTATION_PORT:40500"
    restart: always
    build:
      context: .
      dockerfile: ./apps/qanary-component-pm/Dockerfile
    environment:
      - SPRING_BOOT_ADMIN_URL=$SPRING_BOOT_ADMIN_URL
      - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL=http://$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_REPRESENTATION_NAME:$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_PM_REPRESENTATION_PORT
      - QANARY_ORIGIN=$QANARY_HOST:$QANARY_PORT
      - LUBW_DOMAIN=$PM_REPRESENTATION_DOMAIN
    volumes:
      - ./apps/qanary-component-pm:/app/apps/qanary-component-pm
      - /app/apps/qanary-component-pm/node_modules
      - /app/node_modules

  rasa:
    container_name: rasa-bot
    networks:
      - rasa-network
    ports:
      - "5005:5005"
    build:
      context: ./apps/rasa
    command: >
      run --enable-api --cors "*"

  action-server:
    container_name: action-server
    networks:
      - rasa-network
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./apps/action-server/Dockerfile
    volumes:
      - ./apps/action-server:/app/apps/action-server
      - /app/apps/action-server/node_modules
      - /app/node_modules

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
      - /app/node_modules
    restart: always
    ports:
      - "3000:3000"
    networks:
      - rasa-network

networks:
  rasa-network:
    external: false
