version: "3.5"

services:
  qanary-pipeline:
    container_name: qanary-pipeline
    image: qanary/qanary-pipeline:3.5.1
    restart: always
    networks:
      - rasa-network
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    environment:
      - STARDOG_URL=$STARDOG_URL
      - STARDOG_USERNAME=$STARDOG_USERNAME
      - STARDOG_PASSWORD=$STARDOG_PASSWORD
      - SERVER_HOST=$SERVER_HOST
      - SERVER_PORT=$SERVER_PORT
      - QANARY_PROCESS_ALLOW-ADDITIONAL-TRIPLES=true

  qanary-component:
    container_name: qanary-component
    networks:
      - rasa-network
    restart: always
    ports:
      - "40500:40500"
    build:
      context: .
      dockerfile: ./packages/qanary-component-core/Dockerfile
    volumes:
      - ./packages/qanary-component-core:/app
      - /app/packages/qanary-component-core/node_modules
      - /app/node_modules

  rasa:
    container_name: rasa-bot
    networks:
      - rasa-network
    ports:
      - "5005:5005"
    build:
      context: ./apps/rasa
    command: >
      run --enable-api --cors "*"

  action-server:
    container_name: action-server
    networks:
      - rasa-network
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./apps/action-server/Dockerfile
    volumes:
      - ./apps/action-server:/app/apps/action-server
      - /app/apps/action-server/node_modules
      - /app/node_modules

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    volumes:
      - ./apps/frontend/src:/app/apps/frontend/src
      - ./apps/frontend/public:/app/apps/frontend/public
      - /app/apps/frontend/node_modules
      - /app/node_modules
    restart: always
    ports:
      - "3000:3000"
    networks:
      - rasa-network

networks:
  rasa-network:
    external: false
