version: "3.5"

services:
  qanary-pipeline:
    container_name: qanary-pipeline
    image: qanary/qanary-pipeline:3.5.1
    restart: always
    networks:
      - rasa-network
    ports:
      - "$QANARY_PORT:$QANARY_PORT"
    environment:
      - STARDOG_URL=$STARDOG_URL
      - STARDOG_USERNAME=$STARDOG_USERNAME
      - STARDOG_PASSWORD=$STARDOG_PASSWORD
      - SERVER_HOST=$QANARY_HOST
      - SERVER_PORT=$QANARY_PORT
      - QANARY_PROCESS_ALLOW-ADDITIONAL-TRIPLES=true

  qanary-component-example1:
    container_name: $SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_A_NAME
    networks:
      - rasa-network
    ports:
      - "$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_A_PORT:40500"
    restart: always
    build:
      context: .
      dockerfile: ./apps/qanary-component-example/Dockerfile
    environment:
      - SPRING_BOOT_ADMIN_URL=$SPRING_BOOT_ADMIN_URL
      - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL=http://$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_A_NAME:$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_A_PORT
    volumes:
      - ./packages/qanary-component-example:/app/packages/qanary-component-example
      - /app/packages/qanary-component-example/node_modules
      - /app/node_modules
        
  qanary-component-example2:
    container_name: $SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_B_NAME
    networks:
      - rasa-network
    ports:
      - "$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_B_PORT:40500"
    restart: always
    build:
      context: .
      dockerfile: ./apps/qanary-component-example/Dockerfile
    environment:
      - SPRING_BOOT_ADMIN_URL=$SPRING_BOOT_ADMIN_URL
      - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL=http://$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_B_NAME:$SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_EXAMPLE_B_PORT
    volumes:
      - ./packages/qanary-component-example:/app/packages/qanary-component-example
      - /app/packages/qanary-component-example/node_modules
      - /app/node_modules

  rasa:
    container_name: rasa-bot
    networks:
      - rasa-network
    ports:
      - "5005:5005"
    build:
      context: ./apps/rasa
    command: >
      run --enable-api --cors "*"

  action-server:
    container_name: action-server
    networks:
      - rasa-network
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./apps/action-server/Dockerfile
    volumes:
      - ./apps/action-server:/app/apps/action-server
      - /app/apps/action-server/node_modules
      - /app/node_modules

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
      - /app/node_modules
    restart: always
    ports:
      - "3000:3000"
    networks:
      - rasa-network

networks:
  rasa-network:
    external: false
