import { IQanaryAnnotation } from "../interfaces/annotations";
import { ILUBWData, LUBWDataTransformationService } from "./transformation-service";

/**
 * The aggregated data of the LUBW API.
 */
export interface ILUBWMeasurandData {
  /** fetched measurands of the lubw api */
  measurands: any;
  /** the calculation type */
  calculationType: string;
  /** the representation type */
  representationType: string;
}

/**
 * Service for querying the LUBW API.
 */
export class LUBWQueryService {
  /** transformation service to transform annotations into lubw data */
  private transformationService: LUBWDataTransformationService;

  /** the url to query the LUBW API */
  private apiURL: string;

  /** the transformed LUBW data */
  private lubwData: ILUBWData;

  constructor(annotations: Array<IQanaryAnnotation>) {
    this.transformationService = new LUBWDataTransformationService(annotations);
    this.lubwData = this.transformationService.getTransformedLUBWData();
    this.apiURL = this.getLUBWAPIURL();
  }

  /**
   * Queries the LUBW API with the given annotations.
   * @param annotations the qanary annotations generated by components
   * @returns the data queried from the LUBW API
   */
  public async queryLUBWAPI(): Promise<ILUBWMeasurandData> {
    console.log("Querying LUBW API with URL: " + this.apiURL);

    // TODO: add error handling
    // TODO: add logic for different calculation types
    const response = await fetch(this.apiURL);
    const measurands = await response.json();

    return {
      measurands,
      calculationType: this.lubwData.calculation,
      representationType: this.lubwData.representation,
    };
  }

  /**
   * Transforms the annotations to a valid LUBW API URL.
   * @param annotations the qanary annotations generated by components
   * @returns the constructed LUBW API URL
   */
  private getLUBWAPIURL(): string {
    const lubwData: ILUBWData = this.transformationService.getTransformedLUBWData();

    return `https://lupo-cloud.de/air/metric/kit.iai.test.${lubwData.measurand}?from=${lubwData.time}-ago&labels=station:${lubwData.station}`;
  }
}
