import { differenceInDays } from "date-fns";
import { Domain } from "qanary-lubw-data";

import { IQanaryAnnotation } from "../interfaces/annotations";
import { defaultLUBWData } from "../utils/default-lubw-data";

/**
 * The filtered annotations by domain.
 */
interface IFilteredAnnotations {
  /** annotations of the domain station */
  stationAnnotation: Array<IQanaryAnnotation>;
  /** annotations of the domain measurand */
  measurandAnnotation: Array<IQanaryAnnotation>;
  /** annotations of the domain representation */
  representationAnnotation: Array<IQanaryAnnotation>;
  /** annotations of the domain calculation */
  calculationAnnotation: Array<IQanaryAnnotation>;
  /** annotations of the domain time */
  timeAnnotation: Array<IQanaryAnnotation>;
}

/**
 * The interim internal representation of the LUBW data needed to query the database.
 * TODO: could be multiple instances of the same domain (e.g. multiple stations)
 */
export interface ILUBWData {
  /** the station id*/
  station: string;
  /** the measurand id */
  measurand: string;
  /** the representation format */
  representation: string;
  /** the calculation type */
  calculation: string;
  /** the time as number of days ago*/
  time: string;
}

/**
 * The time object consisting of start and optional end time.
 */
interface ITimeObject {
  /** recognized start date */
  start: string;
  /** recognized end date */
  end?: string;
}

/**
 * Service for transforming the annotations to the intermediate representation format.
 */
export class LUBWDataTransformationService {
  /** the transformed LUBW data from annotation */
  private lubwData: ILUBWData;

  constructor(annotations: Array<IQanaryAnnotation>) {
    this.lubwData = this.transformAnnotationsToLUBWDataRepresentation(annotations);
  }

  /**
   * Gets the transformed LUBW data from annotations.
   * @returns transformed LUBW data
   */
  public getTransformedLUBWData(): ILUBWData {
    return this.lubwData;
  }

  /**
   * Transforms the annotations to the intermediate representation format
   * @param annotations the qanary annotations generated by components
   * @returns the intermediate representation format of the annotations
   */
  private transformAnnotationsToLUBWDataRepresentation(annotations: Array<IQanaryAnnotation>): ILUBWData {
    const filteredAnnotations: IFilteredAnnotations = this.filterAnnotations(annotations);

    return this.transformAndMergeWithDefaultLUBWData(filteredAnnotations);
  }

  /**
   * Transforms the annotations to the interim internal format and merges it with the default LUBW data.
   * @param filteredAnnotations the filtered annotations
   * @returns the interim internal format of the annotations
   */
  private transformAndMergeWithDefaultLUBWData(filteredAnnotations: IFilteredAnnotations): ILUBWData {
    const firstAnnotation = 0;
    const defaultValues: ILUBWData = defaultLUBWData;

    const transformedValues: ILUBWData = {
      station: filteredAnnotations.stationAnnotation[firstAnnotation].hasBody,
      measurand: filteredAnnotations.measurandAnnotation[firstAnnotation].hasBody,
      representation: filteredAnnotations.representationAnnotation[firstAnnotation].hasBody,
      calculation: filteredAnnotations.calculationAnnotation[firstAnnotation].hasBody,
      // TODO: do usefull merge that does not override the default value if custom value is null/undefined
      time: this.transformTime(filteredAnnotations.timeAnnotation[firstAnnotation].hasBody) ?? defaultValues.time,
    };

    return { ...defaultValues, ...transformedValues };
  }

  /**
   * Transforms the time annotation to the interim internal format.
   * @param time the annotated time as serialized JSON
   * @returns the difference between the start and end date in days or null if the transformation failed
   */
  private transformTime(time: string): string | null {
    try {
      const timeObject: ITimeObject = JSON.parse(time) as ITimeObject;

      if (!timeObject.end) {
        throw new Error("The end date is missing. Fallback to default value.");
      }

      const dayDifference = differenceInDays(new Date(timeObject.end), new Date(timeObject.start));

      return `${dayDifference}d`;
    } catch (error) {
      console.error(error);
      return null;
    }
  }

  /**
   * Filters annotation by the domain instances and returns the filtered annotations for each instance.
   * @param annotations all annotations inside the qanary knowledge graph
   * @returns filtered annottions for each domain instance
   */
  private filterAnnotations(annotations: Array<IQanaryAnnotation>): IFilteredAnnotations {
    const stationAnnotation: Array<IQanaryAnnotation> = annotations.filter((annotation) =>
      this.filterAnnotationsByAnnotationType(annotation, Domain.Station),
    );

    const measurandAnnotation: Array<IQanaryAnnotation> = annotations.filter((annotation) =>
      this.filterAnnotationsByAnnotationType(annotation, Domain.Measurand),
    );

    const representationAnnotation: Array<IQanaryAnnotation> = annotations.filter((annotation) =>
      this.filterAnnotationsByAnnotationType(annotation, Domain.Representation),
    );

    const calculationAnnotation: Array<IQanaryAnnotation> = annotations.filter((annotation) =>
      this.filterAnnotationsByAnnotationType(annotation, Domain.Calculation),
    );

    const timeAnnotation: Array<IQanaryAnnotation> = annotations.filter((annotation) =>
      this.filterAnnotationsByAnnotationType(annotation, Domain.Time),
    );

    return {
      stationAnnotation,
      measurandAnnotation,
      representationAnnotation,
      calculationAnnotation,
      timeAnnotation,
    };
  }

  /**
   * Checks whether the given annotation is of annotation type.
   * @param annotation the annotation to check
   * @param annotationType the type to match
   * @returns true if annotation is of annotation type, false otherwise
   */
  private filterAnnotationsByAnnotationType(annotation: IQanaryAnnotation, annotationType: string): boolean {
    return annotation.annotatedBy === annotationType;
  }
}
