= Redis

We use Redis to store session data (context) inside the `action-server`. 

== What is Redis?

Redis is an open-source in-memory data structure store, used as a database, cache and message broker. It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs and geospatial indexes with radius queries.

== Usage

We use redis to store related session data (context), that enhances the functionality of the `action-server` in order to provide a better user experience. 

For example we store the latest `session-id` from rasa and the latest recognized intent in order to handle fallbacks and automatically continue the conversation after a fallback or refinement.

This enables us to handle shortcuts for users and is the basis for our generic fallback mechanism if mandatory data are not provided.

Shortcuts can look like this:

1. Wie ist der Luftqualtitätsindex-Wert in Berlin als Graph? -> `Luftqualtitätsindex`, `Berlin`, `Graph`, `Messwertabfrage` are stored
2. Wie ist es in Ulm? -> `Luftqualtitätsindex`, `Graph`, `Messwertabfrage` are retrieved from session and reused with `Ulm` as new location

Refinements can look like this:
1. Wie ist der Luftqualtitätsindex-Wert representiert als Graph? -> `Luftqualtitätsindex`,`Graph`, `Messwertabfrage` are stored, Station is missing
2. Ich benötige die Station
3. Die Station ist Berlin -> `Luftqualtitätsindex`,`Graph`, `Messwertabfrage` are retrieved and used with `Berlin` as new station to query results