@startuml
skinparam Style strictuml
autonumber
skinparam BoxPadding 15

title Architecture Two Stage Fallback

actor "User"

"User" -> Rasa: Hi
"User" <-- Rasa: Hi

|||

group "First Fallback"
"User" -> Rasa: !#@?!
Rasa -> Rasa: intent classification (confidence < threshold)
Rasa -> Rasa: two_stage_fallback_action

|||

Rasa -> "Action Server": action_default_ask_affirmation
Rasa <-- "Action Server": text + button(affirm/deny)
"User" <-- Rasa: text + button(affirm/deny)

|||

"User" -> Rasa: deny
Rasa -> Rasa: utter_ask_rephrase
"User" <-- Rasa: Rephrase please
end

|||
|||

group "Second Fallback"
"User" -> Rasa: !#@?!
Rasa -> Rasa: intent classification (confidence < threshold)
Rasa -> Rasa: two_stage_fallback_action


|||

Rasa -> "Action Server": action_default_ask_affirmation
Rasa <-- "Action Server": text + button(affirm/deny)
"User" <-- Rasa: text + button(affirm/deny)

|||

"User" -> Rasa: deny
Rasa -> Rasa: default_fallback
"User" <-- Rasa: Could not understand you (restart)
end

@enduml