@startuml Architecture
skinparam Style strictuml
autonumber
skinparam BoxPadding 15

title Architecture Overview

actor "user"

"user" -> Rasa: Wie ist der Ozonwert in Ulm am 23.01.2023\nverglichen mit den Durchschnittswerten\n der letzten 10 Jahre repräsentiert als Text?

Rasa -> Rasa: Intent-Klassifikation

alt Fehler
    autonumber stop
    "Rasa" -> "user": Fallback
end

autonumber 3
Rasa -> "Action Server": action_for_intent

database "State Database"
"Action Server" -> "State Database": Speicherung des Intents

|||

"Action Server" -> Qanary: Pipeline

loop 
Qanary -> "Qanary Component"
Qanary <-- "Qanary Component"
end

"Action Server" <-- Qanary: Annotationen

|||

"Action Server" -> "Action Server": Fakten-Extraktion und Fakten-Transformation

|||

"Action Server" -> "State Database": State-Merging und \nState-Speicherung

|||

"Action Server" -> "Action Server": Verifikation

|||

alt Verifikationsfehler
"Rasa" <-- "Action Server": Fehlerbenachrichtigung
"user" <-- "Rasa": Fehlerbenachrichtigung
end

|||

"Action Server" -> "Action Server": Auslesen des\nursprünglichen Intents

|||

alt Intentfehler
"Rasa" <-- "Action Server": Fehlerbenachrichtigung
"user" <-- "Rasa": Fehlerbenachrichtigung
end

|||

database "LUPO-API"
"Action Server" -> "LUPO-API": Messwertabfrage
"Action Server" <-- "LUPO-API": Messwerte

|||

"Action Server" -> "Action Server": Repräsentations-Erstellung (Chart/Tabelle)

|||

Rasa <-- "Action Server": Antwort-Response
user <-- Rasa: Antwort
@enduml