@startuml
title Architecture Qanary Pipeline

frame "Pattern Matching" {
[Measurand PM]
[Station PM]
[Calculation PM]
[Representation PM]
}

frame "Helpers" {
[LD Shuyo]
}

frame "Advanced Recognition" {
[Customized NER]
[Date AR]
[Fuzzy AR]
}


database TripleStore
start .> [Station PM]
start ..> TripleStore: seeding

[Station PM] <.. TripleStore: stations
[Measurand PM] <.. TripleStore: measurands
[Calculation PM] <.. TripleStore: calculations
[Representation PM] <.. TripleStore: representations
[Fuzzy AR] <.. TripleStore: stations & measruands &\n calculations & representations

[Station PM] -> [Measurand PM]
[Measurand PM] -> [Calculation PM]
[Calculation PM] -> [Representation PM]
[Representation PM] -> [LD Shuyo]

[LD Shuyo] -down-> [Date AR]
[Date AR] -> [Customized NER]
[Customized NER] -> [Fuzzy AR]

[Fuzzy AR] -> end
@enduml