POST http://qanary-pipeline:40111/startquestionansweringwithtextquestion
Content-Type: application/json

{
  "question": "Wie ist der Ozonwert in Ulm am 23.01.2023, verglichen mit den Durchschnittswerten der letzten 10 Jahre repräsentiert als Tabelle?",
  "componentlist": [
    "LD-Shuyo",
    "qanary-component-time"
  ]
}
